// tslint:disable:object-literal-sort-keys
export enum SOURCE_JSON_TO_FULL {
	CoS = "Curse of Strahd",
	DMG = "Dungeon Master's Guide",
	EEPC = "Elemental Evil Player's Companion",
	EET = "Elemental Evil: Trinkets",
	HotDQ = "Hoard of the Dragon Queen",
	LMoP = "Lost Mine of Phandelver",
	Mag = "Dragon Magazine",
	MM = "Monster Manual",
	OotA = "Out of the Abyss",
	PHB = "Player's Handbook",
	PotA = "Princes of the Apocalypse",
	RoT = "The Rise of Tiamat",
	RoTOS = "The Rise of Tiamat Online Supplement",
	SCAG = "Sword Coast Adventurer's Guide",
	SKT = "Storm King's Thunder",
	ToA = "Tomb of Annihilation",
	ToD = "Tyranny of Dragons",
	TTP = "The Tortle Package",
	TftYP = "Tales from the Yawning Portal",
	"TftYP-AtG" = "Tales from the Yawning Portal",
	"TftYP-DiT" = "Tales from the Yawning Portal",
	"TftYP-TFoF" = "Tales from the Yawning Portal",
	"TftYP-THSoT" = "Tales from the Yawning Portal",
	"TftYP-TSC" = "Tales from the Yawning Portal",
	"TftYP-ToH" = "Tales from the Yawning Portal",
	"TftYP-WPM" = "Tales from the Yawning Portal",
	VGM = "Volo's Guide to Monsters",
	XGE = "Xanathar's Guide to Everything",
	OGA = "One Grung Above",
	MTF = "Mordenkainen's Tome of Foes",
	WDH = "Waterdeep: Dragon Heist",
	WDMM = "Waterdeep: Dungeon of the Mad Mage",
	GGR = "Guildmasters' Guide to Ravnica",
	KKW = "Krenko's Way",
	LLK = "Lost Laboratory of Kwalish",
	GoS = "Ghosts of Saltmarsh",
	AI = "Acquisitions Incorporated",
	OoW = "The Orrery of the Wanderer",
	DIP = "Dragon of Icespire Peak",
	HftT = "Hunt for the Thessalhydra",
	DC = "Divine Contention",
	SLW = "Storm Lord's Wrath",
	SDW = "Sleeping Dragon's Wake",
	BGDIA = "Baldur's Gate: Descent Into Avernus",
	LR = "Locathah Rising",
	AL = "Adventurers' League",
	SAC = "Sage Advice Compendium",
	ERLW = "Eberron: Rising from the Last War",
	EFR = "Eberron: Forgotten Relics",
	RMBRE = "The Lost Dungeon of Rickedness: Big Rick Energy",
	RMR = "Dungeons & Dragons vs. Rick and Morty: Basic Rules",
	MFF = "Mordenkainen's Fiendish Folio",
	AWM = "Adventure with Muk",
	IMR = "Infernal Machine Rebuild",
	SADS = "Sapphire Anniversary Dice Set",
	Screen = "Dungeon Master's Screen",
	ALCurseOfStrahd = "Adventurers League: Curse of Strahd",
	ALElementalEvil = "Adventurers League: Elemental Evil",
	ALRageOfDemons = "Adventurers League: Rage of Demons",
	PSA = "Plane Shift: Amonkhet",
	PSI = "Plane Shift: Innistrad",
	PSK = "Plane Shift: Kaladesh",
	PSZ = "Plane Shift: Zendikar",
	PSX = "Plane Shift: Ixalan",
	PSD = "Plane Shift: Dominaria",
	UAArtificer = "Unearthed Arcana: Artificer",
	UAEladrinAndGith = "Unearthed Arcana: Eladrin and Gith",
	UAEberron = "Unearthed Arcana: Eberron",
	UAFeatsForRaces = "Unearthed Arcana: Feats for Races",
	UAFeatsForSkills = "Unearthed Arcana: Feats for Skills",
	UAFiendishOptions = "Unearthed Arcana: Fiendish Options",
	UAFeats = "Unearthed Arcana: Feats",
	UAGothicHeroes = "Unearthed Arcana: Gothic Heroes",
	UAModernMagic = "Unearthed Arcana: Modern Magic",
	UAStarterSpells = "Unearthed Arcana: Starter Spells",
	UATheMysticClass = "Unearthed Arcana: The Mystic Class",
	UAThatOldBlackMagic = "Unearthed Arcana: That Old Black Magic",
	UATheRangerRevised = "Unearthed Arcana: The Ranger, Revised",
	UAWaterborneAdventures = "Unearthed Arcana: Waterborne Adventures",
	UAVariantRules = "Unearthed Arcana: Variant Rules",
	UALightDarkUnderdark = "Unearthed Arcana: Light, Dark, Underdark!",
	UARangerAndRogue = "Unearthed Arcana: Ranger and Rogue",
	UAATrioOfSubclasses = "Unearthed Arcana: A Trio of Subclasses",
	UABarbarianPrimalPaths = "Unearthed Arcana: Barbarian Primal Paths",
	UARevisedSubclasses = "Unearthed Arcana: Revised Subclasses",
	UAKitsOfOld = "Unearthed Arcana: Kits of Old",
	UABardBardColleges = "Unearthed Arcana: Bard: Bard Colleges",
	UAClericDivineDomains = "Unearthed Arcana: Cleric: Divine Domains",
	UADruid = "Unearthed Arcana: Druid",
	UARevisedClassOptions = "Unearthed Arcana: Revised Class Options",
	UAFighter = "Unearthed Arcana: Fighter",
	UAMonk = "Unearthed Arcana: Monk",
	UAPaladin = "Unearthed Arcana: Paladin",
	UAModifyingClasses = "Unearthed Arcana: Modifying Classes",
	UASorcerer = "Unearthed Arcana: Sorcerer",
	UAWarlockAndWizard = "Unearthed Arcana: Warlock and Wizard",
	UATheFaithful = "Unearthed Arcana: The Faithful",
	UAWizardRevisited = "Unearthed Arcana: Wizard Revisited",
	UAElfSubraces = "Unearthed Arcana: Elf Subraces",
	UAMassCombat = "Unearthed Arcana: Mass Combat",
	UAThreePillarExperience = "Unearthed Arcana: Three-Pillar Experience",
	UAGreyhawkInitiative = "Unearthed Arcana: Greyhawk Initiative",
	UAThreeSubclasses = "Unearthed Arcana: Three Subclasses",
	UAOrderDomain = "Unearthed Arcana: Order Domain",
	UACentaursMinotaurs = "Unearthed Arcana: Centaurs and Minotaurs",
	UAGiantSoulSorcerer = "Unearthed Arcana: Giant Soul Sorcerer",
	UARacesOfEberron = "Unearthed Arcana: Races of Eberron",
	UARacesOfRavnica = "Unearthed Arcana: Races of Ravnica",
	UAWGE = "Wayfinder's Guide to Eberron",
	UAOfShipsAndSea = "Unearthed Arcana: Of Ships and the Sea",
	UASidekicks = "Unearthed Arcana: Sidekicks",
	UAArtificerRevisited = "Unearthed Arcana: Artificer Revisited",
	UABarbarianAndMonk = "Unearthed Arcana: Barbarian and Monk",
	UASorcererAndWarlock = "Unearthed Arcana: Sorcerer and Warlock",
	UABardAndPaladin = "Unearthed Arcana: Bard and Paladin",
	UAClericDruidWizard = "Unearthed Arcana: Cleric, Druid, and Wizard",
	UAFighterRangerRogue = "Unearthed Arcana: Fighter, Ranger, and Rogue",
	UAClassFeatureVariants = "Unearthed Arcana: Class Feature Variants",
	UAFighterRogueWizard = `Unearthed Arcana: Fighter, Rogue, and Wizard`,
	UA2020SubclassesPt1 = `Unearthed Arcana: 2020 Subclasses, Part 1`,
	Stream = "Livestream",
	Twitter = "Twitter",
	SRD = "5e System Reference Document",
}
export type SOURCE_KEY = keyof typeof SOURCE_JSON_TO_FULL;

export const SOURCE_JSON_TO_SHORT: { [key in SOURCE_KEY]: string } = {
	"CoS": "CoS",
	"DMG": "DMG",
	"EEPC": "EEPC",
	"EET": "EET",
	"HotDQ": "HotDQ",
	"LMoP": "LMoP",
	"Mag": "Mag",
	"MM": "MM",
	"OotA": "OotA",
	"PHB": "PHB",
	"PotA": "PotA",
	"RoT": "RoT",
	"RoTOS": "RoTOS",
	"SCAG": "SCAG",
	"SKT": "SKT",
	"ToA": "ToA",
	"ToD": "ToD",
	"TTP": "TTP",
	"TftYP": "TftYP",
	"TftYP-AtG": "TftYP",
	"TftYP-DiT": "TftYP",
	"TftYP-TFoF": "TftYP",
	"TftYP-THSoT": "TftYP",
	"TftYP-TSC": "TftYP",
	"TftYP-ToH": "TftYP",
	"TftYP-WPM": "TftYP",
	"VGM": "VGM",
	"XGE": "XGE",
	"OGA": "OGA",
	"MTF": "MTF",
	"WDH": "WDH",
	"WDMM": "WDMM",
	"GGR": "GGR",
	"KKW": "KKW",
	"LLK": "LLK",
	"GoS": "GoS",
	"AI": "AI",
	"OoW": "OoW",
	"DIP": "DIP",
	"HftT": "HftT",
	"DC": "DC",
	"SLW": "SLW",
	"SDW": "SDW",
	"BGDIA": "BGDIA",
	"LR": "LR",
	"AL": "AL",
	"SAC": "SAC",
	"ERLW": "ERLW",
	"EFR": "EFR",
	"RMBRE": "RMBRE",
	"RMR": "RMR",
	"MFF": "MFF",
	"AWM": "AWM",
	"IMR": "IMR",
	"SADS": "SADS",
	"Screen": "Screen",
	"ALCurseOfStrahd": "ALCoS",
	"ALElementalEvil": "ALEE",
	"ALRageOfDemons": "ALRoD",
	"PSA": "PSA",
	"PSI": "PSI",
	"PSK": "PSK",
	"PSZ": "PSZ",
	"PSX": "PSX",
	"PSD": "PSD",
	"UAArtificer": "UAA",
	"UAEladrinAndGith": "UAEaG",
	"UAEberron": "UAEB",
	"UAFeatsForRaces": "UAFFR",
	"UAFeatsForSkills": "UAFFS",
	"UAFiendishOptions": "UAFO",
	"UAFeats": "UAFT",
	"UAGothicHeroes": "UAGH",
	"UAModernMagic": "UAMM",
	"UAStarterSpells": "UASS",
	"UATheMysticClass": "UAM",
	"UAThatOldBlackMagic": "UAOBM",
	"UATheRangerRevised": "UATRR",
	"UAWaterborneAdventures": "UAWA",
	"UAVariantRules": "UAVR",
	"UALightDarkUnderdark": "UALDU",
	"UARangerAndRogue": "UARAR",
	"UAATrioOfSubclasses": "UAATOSC",
	"UABarbarianPrimalPaths": "UABPP",
	"UARevisedSubclasses": "UARSC",
	"UAKitsOfOld": "UAKoO",
	"UABardBardColleges": "UABBC",
	"UAClericDivineDomains": "UACDD",
	"UADruid": "UAD",
	"UARevisedClassOptions": "UARCO",
	"UAFighter": "UAF",
	"UAMonk": "UAM",
	"UAPaladin": "UAP",
	"UAModifyingClasses": "UAMC",
	"UASorcerer": "UAS",
	"UAWarlockAndWizard": "UAWAW",
	"UATheFaithful": "UATF",
	"UAWizardRevisited": "UAWR",
	"UAElfSubraces": "UAESR",
	"UAMassCombat": "UAMAC",
	"UAThreePillarExperience": "UA3PE",
	"UAGreyhawkInitiative": "UAGHI",
	"UAThreeSubclasses": "UATSC",
	"UAOrderDomain": "UAOD",
	"UACentaursMinotaurs": "UACAM",
	"UAGiantSoulSorcerer": "UAGSS",
	"UARacesOfEberron": "UARoE",
	"UARacesOfRavnica": "UARoR",
	"UAWGE": "WGE",
	"UAOfShipsAndSea": "UAOSS",
	"UASidekicks": "UASIK",
	"UAArtificerRevisited": "UAAR",
	"UABarbarianAndMonk": "UABAM",
	"UASorcererAndWarlock": "UASAW",
	"UABardAndPaladin": "UABAP",
	"UAClericDruidWizard": "UACDW",
	"UAFighterRangerRogue": "UAFRR",
	"UAClassFeatureVariants": "UACFV",
	"UAFighterRogueWizard": "UAFRW",
	"UA2020SubclassesPt1": "UA2020SC1",
	"Stream": "Stream",
	"Twitter": "Twitter",
	"SRD": "SRD",
};

export type ABILITIES = "strength" | "dexterity" | "constitution" | "intelligence" | "wisdom" | "charisma";
export type ABILITY_SHORT = keyof typeof ABILITY_DISPLAY;
export enum ABILITY_DISPLAY {
	str = "Strength",
	dex = "Dexterity",
	con = "Constitution",
	int = "Intelligence",
	wis = "Wisdom",
	cha = "Charisma",
}

export type SKILL = keyof typeof SKILL_SHORT;
export enum SKILL_SHORT {
	"acrobatics" = "acro",
	"animal handling" = "hndl",
	"arcana" = "arc",
	"athletics" = "ath",
	"deception" = "decp",
	"history" = "hist",
	"insight" = "ins",
	"intimidation" = "intm",
	"investigation" = "invn",
	"medicine" = "med",
	"nature" = "natr",
	"perception" = "perp",
	"performance" = "perf",
	"persuasion" = "pers",
	"religion" = "reli",
	"sleight of hand" = "soh",
	"stealth" = "slth",
	"survival" = "surv",
}

export const SKILL_TO_ABILITY_SHORT: { [skill in SKILL]: ABILITY_SHORT } = {
	"acrobatics": "dex",
	"animal handling": "wis",
	"arcana": "int",
	"athletics": "str",
	"deception": "cha",
	"history": "int",
	"insight": "wis",
	"intimidation": "cha",
	"investigation": "int",
	"medicine": "wis",
	"nature": "int",
	"perception": "wis",
	"performance": "cha",
	"persuasion": "cha",
	"religion": "int",
	"sleight of hand": "dex",
	"stealth": "dex",
	"survival": "wis",
};

export type SIZE_KEYS = keyof typeof SIZE;
export enum SIZE {
	F = "Fine",
	D = "Diminutive",
	T = "Tiny",
	S = "Small",
	M = "Medium",
	L = "Large",
	H = "Huge",
	G = "Gargantuan",
	C = "Colossal",
	V = "Varies",
}

export enum TIME_DISPLAY {
	action = "Action",
	bonus = "Bonus Action",
	reaction = "Reaction",
	round = "Rounds",
	minute = "Minutes",
	hour = "Hours",
}
export type TIMES = keyof typeof TIME_DISPLAY;

export type TYPES = "aberration" | "beast" | "celestial" | "construct" | "dragon" | "elemental" | "fey" | "fiend" | "giant" | "humanoid" | "monstrosity"
	| "ooze" | "plant" | "undead";

export type SPELL_SCHOOL_KEYS = keyof typeof SPELL_SCHOOL_DISPLAY;
export enum SPELL_SCHOOL_DISPLAY {
	A = "Abjuration",
	V = "Evocation",
	E = "Enchantment",
	I = "Illusion",
	D = "Divination",
	N = "Necromancy",
	T = "Transmutation",
	C = "Conjuration",
	P = "Psionic",
}

export enum SPELL_SCHOOL_SHORT {
	A = "Abj.",
	V = "Evoc.",
	E = "Ench.",
	I = "Illu.",
	D = "Divin.",
	N = "Necro.",
	T = "Trans.",
	C = "Conj.",
	P = "Psi.",
}

export type ARMOR_KEYS = keyof typeof ARMOR;
export enum ARMOR {
	"l." = "light",
	"m." = "medium",
	"h." = "heavy",
}

export type ITEM_TYPE_KEYS = keyof typeof ITEM_TYPE;
export enum ITEM_TYPE {
	A = "Ammunition",
	AF = "Ammunition",
	AT = "Artisan Tool",
	EM = "Eldritch Machine",
	EXP = "Explosive",
	G = "Adventuring Gear",
	GS = "Gaming Set",
	HA = "Heavy Armor",
	INS = "Instrument",
	LA = "Light Armor",
	M = "Melee Weapon",
	MA = "Medium Armor",
	MNT = "Mount",
	GV = "Generic Variant",
	P = "Potion",
	R = "Ranged Weapon",
	RD = "Rod",
	RG = "Ring",
	S = "Shield",
	SC = "Scroll",
	SCF = "Spellcasting Focus",
	OTH = "Other",
	T = "Tool",
	TAH = "Tack and Harness",
	TG = "Trade Good",
	VEH = "Vehicle (land)",
	SHP = "Vehicle (water)",
	AIR = "Vehicle (air)",
	WD = "Wand",
}

export type DAMAGE_TYPE_KEY = keyof typeof DAMAGE_TYPE;
export enum DAMAGE_TYPE {
	A = "acid",
	B = "bludgeoning",
	C = "cold",
	F = "fire",
	O = "force",
	L = "lightning",
	N = "necrotic",
	P = "piercing",
	I = "poison",
	Y = "psychic",
	R = "radiant",
	S = "slashing",
	T = "thunder",
}

export type CONDITIONS = "blinded" | "charmed" | "deafened" | "exhaustion" | "frightened" | "grappled" | "incapacitated" | "invisible" | "paralyzed"
	| "petrified" | "poisoned" | "prone" | "restrained" | "stunned" | "unconscious";

export type RANGE = "special" | "point" | "line" | "cube" | "cone" | "radius" | "sphere" | "hemisphere" | "cylinder";
export type DISTANCE = "feet" | "miles" | "self" | "touch" | "unlimited" | "plane" | "sight";
export type CASTING_DURATION_TYPE = "instant" | "timed" | "permanent" | "special";
export type CASTING_DURATION = "hour" | "minute" | "turn" | "round" | "week" | "day" | "year";

export type SPELL_AREA_TYPE_KEY = keyof typeof SPELL_AREA_TYPE;
export enum SPELL_AREA_TYPE {
	ST = "Single Target",
	MT = "Multiple Targets",
	C = "Cube",
	N = "Cone",
	Y = "Cylinder",
	S = "Sphere",
	R = "Circle",
	Q = "Square",
	L = "Line",
	H = "Hemisphere",
	W = "Wall",
}

export type SPELL_ATTACK_TYPE_KEY = keyof typeof SPELL_ATTACK_TYPE;
export enum SPELL_ATTACK_TYPE {
	M = "Melee",
	R = "Ranged",
	O = "Other/Unknown",
}

export type WEAPON_ATTACK_TYPE_KEY = keyof typeof WEAPON_ATTACK_TYPE;
export enum WEAPON_ATTACK_TYPE {
	MW = "Melee Weapon Attack",
	RW = "Ranged Weapon Attack",
}

export type ALIGNMENT_KEY = keyof typeof ALIGNMENT;
export enum ALIGNMENT {
	"L" = "Lawful",
	"N" = "Neutral",
	"NX" = "Neutral (Law/Chaos axis)",
	"NY" = "Neutral (Good/Evil axis)",
	"C" = "Chaotic",
	"G" = "Good",
	"E" = "Evil",
	"U" = "Unaligned",
	"A" = "Any alignment",
}

export type SPELL_ENDS_KEY = keyof typeof SPELL_ENDS;
export enum SPELL_ENDS {
	dispel = "dispeled",
	trigger = "triggered",
	discharge = "discharged",
}

export type ITEM_RARITIES = "Rare" | "None" | "Uncommon" | "Very Rare" | "Legendary" | "Artifact" | "Unknown" | "Common" | "Unknown (Magic)" | "Varies";
export type ITEM_PROPERTIES = "T" | "V" | "H" | "2H" | "F" | "L" | "R" | "A" | "LD" | "S" | "AF" | "RLD" | "BF" | "EM" | "OTH";

export type TOOL_PROFICIENCIES = "artisan's tools" | "cartographer's tools" | "disguise kit" | "forgery kit" | "gaming set" | "herbalism kit"
	| "musical instrument" | "navigator's tools" | "thieves' tools" | "vehicles (land)" | "vehicles (water)" | "alchemist's supplies";

export type ENVIRONMENT = "underwater" | "coastal" | "mountain" | "grassland" | "hill" | "arctic" | "urban" | "forest" | "swamp" | "underdark" | "desert";

export type DRAGON_COLORS = "B" | "U" | "G" | "R" | "W" | "A" | "Z" | "C" | "O" | "S";

export type SPELLCASTING_TAG_KEYS = keyof typeof SPELLCASTING_TAGS;
export enum SPELLCASTING_TAGS {
	"P" = "Psionics",
	"I" = "Innate",
	"F" = "Form Only",
	"S" = "Shared",
	"CB" = "Class, Bard",
	"CC" = "Class, Cleric",
	"CD" = "Class, Druid",
	"CP" = "Class, Paladin",
	"CR" = "Class, Ranger",
	"CS" = "Class, Sorcerer",
	"CL" = "Class, Warlock",
	"CW" = "Class, Wizard",
}

export type MISC_TAG_KEYS = keyof typeof MISC_TAGS;
export enum MISC_TAGS {
	"AOE" = "Has Areas of Effect",
	"MW" = "Has Melee Weapon Attacks",
	"RW" = "Has Ranged Weapon Attacks",
	"RNG" = "Has Ranged Weapons",
	"RCH" = "Has Reach Attacks",
	"THW" = "Has Thrown Weapons",
}

export type SENSE_KEYS = keyof typeof SENSES;
export enum SENSES {
	"B" = "blindsight",
	"D" = "darkvision",
	"SD" = "superior darkvision",
	"T" = "tremorsense",
	"U" = "truesight",
}

export type LANGUAGES = keyof typeof LANGUAGE_MAP;
export enum LANGUAGE_MAP {
	"Abyssal" = "AB",
	"Aquan" = "AQ",
	"Auran" = "AU",
	"Celestial" = "CE",
	"Common" = "C",
	"can't speak" = "CS",
	"Draconic" = "DR",
	"Dwarvish" = "D",
	"Elvish" = "E",
	"Giant" = "GI",
	"Gnomish" = "G",
	"Goblin" = "GO",
	"Halfling" = "H",
	"Infernal" = "I",
	"Orc" = "O",
	"Primordial" = "P",
	"Sylvan" = "S",
	"Terran" = "T",
	"Undercommon" = "U",
	"Aarakocra" = "OTH",
	"one additional" = "X",
	"Blink Dog" = "OTH",
	"Bothii" = "OTH",
	"Bullywug" = "OTH",
	"one other language" = "X",
	"plus six more" = "X",
	"plus two more languages" = "X",
	"up to five other languages" = "X",
	"Druidic" = "DU",
	"Giant Eagle" = "OTH",
	"Giant Elk" = "OTH",
	"Giant Owl" = "OTH",
	"Gith" = "GTH",
	"Grell" = "OTH",
	"Grung" = "OTH",
	"Homarid" = "OTH",
	"Hook Horror" = "OTH",
	"Ice Toad" = "OTH",
	"Ixitxachitl" = "OTH",
	"Kruthik" = "OTH",
	"Netherese" = "OTH",
	"Olman" = "OTH",
	"Otyugh" = "OTH",
	"Primal" = "OTH",
	"Sahuagin" = "OTH",
	"Sphinx" = "OTH",
	"Thayan" = "OTH",
	"Thri-kreen" = "OTH",
	"Tlincalli" = "OTH",
	"Troglodyte" = "OTH",
	"Umber Hulk" = "OTH",
	"Vegepygmy" = "OTH",
	"Winter Wolf" = "OTH",
	"Worg" = "OTH",
	"Yeti" = "OTH",
	"Yikaria" = "OTH",
	"all" = "XX",
	"all but rarely speaks" = "XX",
	"any one language" = "X",
	"any two languages" = "X",
	"any three languages" = "X",
	"any four languages" = "X",
	"any five languages" = "X",
	"any six languages" = "X",
	"one language of its creator's choice" = "X",
	"two other languages" = "X",
	"telepathy" = "TP",
	"thieves' cant" = "TC",
	"Thieves' cant" = "TC",
	"Deep Speech" = "DS",
	"Gnoll" = "OTH",
	"Ignan" = "IG",
	"Modron" = "OTH",
	"Slaad" = "OTH",
	"all languages" = "XX",
	"any language" = "X",
}

export type CR_VALUE = keyof typeof CR_TO_XP_MAP;
export const CR_TO_XP_MAP = {
	"Unknown": "Unknown",
	"0": "0 or 10",
	"1/8": 25,
	"1/4": 50,
	"1/2": 100,
	"1": 200,
	"2": 450,
	"3": 700,
	"4": 1100,
	"5": 1800,
	"6": 2300,
	"7": 2900,
	"8": 3900,
	"9": 5000,
	"10": 5900,
	"11": 7200,
	"12": 8400,
	"13": 10000,
	"14": 11500,
	"15": 13000,
	"16": 15000,
	"17": 18000,
	"18": 20000,
	"19": 22000,
	"20": 25000,
	"21": 30000,
	"22": 41000,
	"23": 50000,
	"24": 62000,
	"25": 75000,
	"26": 90000,
	"27": 105000,
	"28": 120000,
	"29": 135000,
	"30": 155000,
};
